### ISSUE TITLE
Einen Teilen-Button für OG-Termine

### ISSUE THREAD

**Issue by ki-ks** [AppFridaysForFutureDE/frontend#104]
(aka. Streik-Teilen-Button?)

**Comment by NikolaiKircher** [comment]
Vermutlich so:
Neuer "Teilen" Button in der App neben dem Streik Termin:
Beim drauf klicken, kann man z.B. über Whatsapp einen Link teilen.
Dieser Link routet über das backend (neue route) zurück in die App.

Zu klären: 
Was passiert, wenn man die App installiert hat und auf den link klickt?
- Öffnen der Karte?
- Neue Seite mit der OG?

**Comment by Conarius** [comment]
Beim Teilen wird einfach ein Text losgeschickt mit den wichtigsten Infos.
