### ISSUE TITLE
iPhone 6s Iphone 7  Anzeigefehler der Netzstreikseite

### ISSUE THREAD

**Issue by JorisJH** [AppFridaysForFutureDE/frontend#166]
IOS 13.4.5

**Comment by JorisJH** [comment]
Scheint mit der neuen Version mehr oder weniger behoben zu sein. 
Nur bei verschiedenen Schriftgrößen wird es schwierig.

**Comment by craeosh** [comment]
Tritt bei einem iPhone SE (1. Generation) auch auf...
Meinst du, dass es in der Version 1.0.2 behoben ist?

**Comment by craeosh** [comment]
![IMG_2852](https://user-images.githubusercontent.com/61389509/82759349-38901c80-9ded-11ea-9dbb-afc647b78360.PNG)

So sieht's auf nem iPhone SE (1. Generation) aus

**Comment by craeosh** [comment]
Evlt. könnte man das lösen, indem man eine Scroll-View einbaut oder die Textgröße dynamisch verkleinert.

**Comment by Conarius** [comment]
TextOverflow einstellen (Erklärung: Bei zu viel Text wird er mit ... abgekürzt)

**Comment by craeosh** [comment]
Klingt ganz gut. Das Problem dabei: "TextOverflow.ellipsis" braucht eine "maxLine" Angabe, damit es sinnvoll ist. Setzt man diese auf 4 ist der Fehler behoben, man sieht aber auch auf anderen Geräten nur noch diese 4 Zeilen obwohl da genug Platz wäre. 
Da müsste man also irgendwie zwischen den Geräten unterscheiden oder doch einen scrollbaren Text draus machen (wobei ich nicht weiß wie das geht).

**Comment by craeosh** [comment]
![Simulator Screen Shot - iPhone SE (1st) - 2020-06-07 at 12 48 21](https://user-images.githubusercontent.com/61389509/83966903-60878180-a8bd-11ea-8c3e-4d40b31bf0e4.png)

So wäre es behoben. Aber auf größeren Geräten gäbe es dann ebenfalls nur 4 Zeilen:
`overflow: TextOverflow.ellipsis, maxLines: 4,`

Weiß jemand wie man diese dynamisch einstellen kann?
