### ISSUE TITLE
Abkürzung im Titel von Bundesweite Arbeitsgruppen

### ISSUE THREAD

**Issue by NikolaiKircher** [AppFridaysForFutureDE/frontend#167]
Die Überschrift "Bundesweite Arbeitsgruppen" ist sehr stark abgekürzt, obwohl noch viel Platz ist.

![Screenshot_20200422-164742](https://user-images.githubusercontent.com/14280211/79997907-57cc1f00-84ba-11ea-91c2-eff9d850f2c8.jpg)

Feedback:
"Bundesweite AGs - Die Überschrift wird gekürzt, obwohl noch massig Platz ist, da ein AGs hinzuschreiben"

Lösungsideen:
- Wort umbruch/abkürzung verbessern
- oder evtl. Titel auf AG ändern

**Comment by Conarius** [comment]
"Arbeitsgruppen" zu "AG" ändern
"AG" (Im Text) auf "AG (Arbeitsgruppen)" ändern
