### ISSUE TITLE
API-Key

### ISSUE THREAD

**Issue by jugendhacker** [AppFridaysForFutureDE/frontend#169]
https://github.com/AppFridaysForFutureDE/frontend/blob/master/android/app/google-services.json scheint öffentlich einen API-Key zu enthalten, ich würde dringend raten, falls dies ein valider Key ist, diesen aus der gesamten History zu entfernen und ihn neu zu generien bzw. den alten invalid zu machen.

**Comment by redsolver** [comment]
Da er ausschliesslich zur Registrierung für Push-Benachrichtigungen verwendet wird und wir keine weiteren Firebase Dienste nutzen, lässt sich der Key nicht wirklich missbrauchen. Der jeweilige Push Dienst prüft auch jeweils die App Signatur, ein eigener Build mit Push-Nachrichten ist also auch nicht möglich.

**Comment by jugendhacker** [comment]
Okay dann ist das ja wenig Problematisch.
