### ISSUE TITLE
Lags bei Bedienung in Netzstreikkarte

### ISSUE THREAD

**Issue by gregthwuen** [AppFridaysForFutureDE/frontend#171]
Die Bedienung der Netzstreikkarte laggt bei Anzeige aller Inhalte extrem, bis zur Unbedienbarkeit (System: Android 10), was vermutlich mit lazy loading vermieden werden könnte.

**Comment by JorisJH** [comment]
Ist bekannt welche Version benutzt wurde?

**Comment by gregthwuen** [comment]
> Ist bekannt welche Version benutzt wurde? 

1.0.5, würd mich aber wundern, wenn's in vorherigen Versionen besser gewesen wäre.

**Comment by JorisJH** [comment]
ich hab nämlich irgendwann in so einer Hauruck aktion noch caching implementiert. und in einer älteren version wird der Build noch deutlich inefizienter ausgeführt. Deswegen wäre es relevent

**Comment by JorisJH** [comment]
unter About us sieht man die Version. Falls du den Error hast wäre es super falls du einmal selber nachguckst und oder die Person fragst die diesen Fehler hat

**Comment by gregthwuen** [comment]
> ich hab nämlich irgendwann in so einer Hauruck aktion noch caching implementiert. und in einer älteren version wird der Build noch deutlich inefizienter ausgeführt. Deswegen wäre es relevent

Es ist die Version 1.0.5, wie ich bereits schrieb.
Und es gibt keinen Error, die Karte hängt sich am Anfang für eine Sekunde auf und danach bleibt die Bedienung sehr ruckelnd. Sind hingegen nur die wenigen „Featured Einträge“ eingeblendet, ist alles verhältnismäßig flüssig.
Daher vermute ich, dass unsichtbare Einträge, die erst beim näher zoomen sichtbar werden, unnötig geladen werden und so das Problem verursachen.

**Comment by jugendhacker** [comment]
Ich kann mit der Version 1.1.0 aus dem Playsore (also `.official`) dieses Problem auf meinem Samsung J5 2015 (SM-J500FN bzw j5nlte) unter Lineage OS 17.1 verlässlich reproduzieren. Wenn ich die Netzstreik Karte auf mache hängt es erst 20-30sec oder so und dann kann ich die Karte nur noch sehr ruckelig bedienen, was noch schlimmer wird wenn ich die Karte verschiebe so das ich über Deutschland bin.

**Comment by NikolaiKircher** [comment]
Die Streikkarte ist momentan nicht aktiv und durch andere Aktionen ersetzt.
Falls wir sie wieder einbauen werden wir versuchen sie möglichst performant zu gestalten.
