### ISSUE TITLE
Paketname APK und Play Store vereinheitlichen

### ISSUE THREAD

**Issue by gregthwuen** [AppFridaysForFutureDE/frontend#172]
In GitHub (und der standalone APK) ist der Package Name `de.fridaysforfuture.app`, im Play Store allerdings `de.fridaysforfuture.app.official`. So wird die App einfach doppelt installiert, was zu Verwirrung und im schlimmsten Fall zu Konflikten führen kann. Optimalerweise den einfacheren Namen ohne official behalten...

**Comment by redsolver** [comment]
Der Name für die Google Play Version musste geändert werden, da Google den Paketnamen `de.fridaysforfuture.app` gesperrt hat. `de.fridaysforfuture.app.official` ist jetzt außerdem konsistent mit der iOS Bundle ID wo aus ähnlichen Gründen die Bundle ID angepasst werden musste

**Comment by redsolver** [comment]
Durch #173 wird jetzt auch die nächste APK mit neuem Package Name erscheinen

**Comment by gregthwuen** [comment]
Schade, aber danke für die Info

**Comment by jugendhacker** [comment]
@redsolver aber cool wäre dann wenigstens ein DAU freundlicher import/export damit die Leute umziehen können...

**Comment by redsolver** [comment]
Ein Export/Import Tool würde hier mMn nur unnötige Komplexität und weitere Probleme hinzufügen, eigentlich müssen nur die eigenen Ortsgruppen nochmal abonniert werden.

**Comment by jugendhacker** [comment]
Okay aus Erfahrung kann ich aber sagen das ihr euch vmtl auf sehr viele Fragen á la "warum sind meine Daten jetzt weg" einstellen müsst....
