### ISSUE TITLE
Alle Buttons in der App benennen 

### ISSUE THREAD

**Issue by JorisJH** [AppFridaysForFutureDE/frontend#175]
Aus Accesibility gründen sollten alle Buttons in der App sinvoll benannt werden

**Comment by NikolaiKircher** [comment]
[VoiceOver_Verbesserung_AppforFuture.pdf.pdf](https://github.com/AppFridaysForFutureDE/frontend/files/4658216/VoiceOver_Verbesserung_AppforFuture.pdf.pdf)

**Comment by craeosh** [comment]
Ist da schon jemand dran?
Wenn mir jemand sagt wie man das technisch umsetzt kann ich das machen. Ist dann ja nur Fleißarbeit. Oder gab's nicht jemanden, der dafür in die AG gekommen ist?
