### ISSUE TITLE
Einstellungen: Newskategorie Abonnements werden nach Änderung ausgeblendet 

### ISSUE THREAD

**Issue by NikolaiKircher** [AppFridaysForFutureDE/frontend#198]
Wenn ich in die Einstellung gehe und einen Regler verändere dann verschwinden alle Newskategorie Abonnements bis ich die Einstellung schließe und wieder öffne.

Android v1.2.3

**Comment by redsolver** [comment]
Konnte ich leider nicht reproduzieren, ein Beispiel-Video wäre super

**Comment by Conarius** [comment]
Aufnahme vom Bug siehe Nachrichtenlink von Discord (Anwendung muss dabei offen sein):  https://canary.discordapp.com/channels/668858000294936600/668859284959789066/736577647387213875

**Comment by craeosh** [comment]
https://cdn.discordapp.com/attachments/744137657323356263/755448486962528324/video0.mov

**Comment by redsolver** [comment]
behoben in https://github.com/AppFridaysForFutureDE/frontend/commit/85fb2c065bfbb20aa6aa7edd43418d75a408d63a
