### ISSUE TITLE
OG Frankfurt am Main doppelt

### ISSUE THREAD

**Issue by Jouaux** [AppFridaysForFutureDE/frontend#208]
Es existiert sowohl die OG Frankfurt am Main auf der Karte als auch Frankfurt letztere kann entfernt werden da keine Infos dazu vorliegen

**Comment by redsolver** [comment]
Wir haben den Fehler weitergeleitet, die Website-AG kümmert sich drum (von denen haben wir die Daten).

**Comment by redsolver** [comment]
Wurde behoben
