### ISSUE TITLE
Grundaussehen OG-Infos inkl. neuem Kartendialog

### ISSUE THREAD

**Issue by redsolver** [AppFridaysForFutureDE/frontend#212]
![unknown (4)](https://user-images.githubusercontent.com/30355444/91465028-91a89a00-e88d-11ea-8732-87f3a025911d.png)
![unknown (5)](https://user-images.githubusercontent.com/30355444/91465035-92413080-e88d-11ea-9681-ebc1555fd1b5.png)
![unknown (6)](https://user-images.githubusercontent.com/30355444/91465037-93725d80-e88d-11ea-888f-e479e22f626b.png)

- oben Karte und Suche:
- Kartensymbol verlinkt zur bisherigen Karte, klicken auf Ort öffnet Popup, Anschauen öffnet im Popup die gleichen Infos, die man auch angezeigt, bekommt, wenn man sie abonniert hat, i-Symbol wechselt zur Infoseite zurück
- Suchen nach Ortsnamen
- Keine OG abonniert: Kartenbutton groß in die Mitte
- OG abonniert: 
- Überschrift des Ortes in Hellblau, komplett wegklappbar
- Nächste Demo mit Bild, Datum, Uhrzeit, Startpunkt
- Nächstes Plenum mit Uhrzeit
- “Sonstiges” in grau, ein- und ausklappbar
- Drei Punkte: Sämtliche Verlinkungen

**Comment by NikolaiKircher** [comment]
anstatt tausend aus- und einfahrbare elemente zu erstellen, die der user klicken muss könnten wir evtl überlegen etwas hiervon zu verwenden?
https://www.youtube.com/watch?v=ORiTTaVY6mM
SliverList & SliverGrid
