### ISSUE TITLE
Grundaussehen Über-uns

### ISSUE THREAD

**Issue by redsolver** [AppFridaysForFutureDE/frontend#213]
![unknown (7)](https://user-images.githubusercontent.com/30355444/91465219-cf0d2780-e88d-11ea-91e6-60e0f199a4f3.png)

- Kacheln als Buttons mit individuellem Symbol und Text, bei Klick Verlinkung
- pro Zeile einheitliches Farbmuster
- Weiteres verlinkt zu Impressum, Datenschutzerklärung

**Comment by NikolaiKircher** [comment]
@JNTV den spenden button können wir leider nicht umsetzen (-> fällt weg), ich glaube also dass dann "webseite" und "social media" sich einfach den platz in der zeile teilen.
