### ISSUE TITLE
Text bei Artikeln abgeschnitten

### ISSUE THREAD

**Issue by craeosh** [AppFridaysForFutureDE/frontend#237]
Bei einigen Android Geräten ist der Text von Artikeln an der rechten Seite abgeschnitten.
Siehe dieses Bild:
https://cdn.discordapp.com/attachments/744137657323356263/777090037329690644/Screenshot_20201114-093807.jpg

**Comment by NikolaiKircher** [comment]
Das passiert immer an Stellen, an denen wir das HTML widget verwenden.

Nachstellen lässt sich das, indem man die Textgröße in den Android/ IOS Settings global erhöht.

Es kann sein, dass das mit Flutter version 1.22 gefixed wurde (Ich glaube wir sind grad bei 1.20)
https://github.com/Sub6Resources/flutter_html/issues/308

Ansonsten gibt es hier vielleicht einen Lösungsvorschlag?
https://github.com/Sub6Resources/flutter_html/issues/294

Ich hab die threads nur überflogen...
